# Generated by Django 4.1.5 on 2023-02-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField()),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='skill_trees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=30)),
                ('number_of_nodes', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('created_at', models.DateTimeField(max_length=30)),
                ('description', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
            options={
                'db_table': 'skill_trees',
            },
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='user_skill_trees_node_completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=128)),
                ('skill_trees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_trees')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
            options={
                'db_table': 'user_skill_trees_node_completion',
            },
        ),
        migrations.CreateModel(
            name='skill_trees_nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_nodes', models.IntegerField()),
                ('parent_skill_trees_node', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
                ('skill_trees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_trees')),
            ],
            options={
                'db_table': 'skill_trees_nodes',
            },
        ),
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_nodes', models.IntegerField()),
                ('skill_trees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_trees')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
            options={
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comments')),
                ('skill_trees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.skill_trees')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='dislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comments')),
                ('skill_trees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.skill_trees')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
            options={
                'db_table': 'dislikes',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='skill_trees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.skill_trees'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user'),
        ),
    ]
