# Generated by Django 4.1.5 on 2023-01-26 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField()),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='skill_tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number_of_nodes', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('created_at', models.DateTimeField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_skill_tree_node_completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_tree')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
        ),
        migrations.CreateModel(
            name='skill_tree_nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_nodes', models.IntegerField()),
                ('parent_skill_tree_node_id', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
                ('skill_tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_tree')),
            ],
        ),
        migrations.AddField(
            model_name='skill_tree',
            name='tag_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tags'),
        ),
        migrations.AddField(
            model_name='skill_tree',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user'),
        ),
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_nodes', models.IntegerField()),
                ('skill_tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_tree')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comments')),
                ('skill_tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_tree')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
        ),
        migrations.CreateModel(
            name='dislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comments')),
                ('skill_tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_tree')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='skill_tree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill_tree'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth_user'),
        ),
    ]
