# Generated by Django 4.1.5 on 2023-01-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auth_user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='dislikes',
            table='dislikes',
        ),
        migrations.AlterModelTable(
            name='likes',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='progress',
            table='progress',
        ),
        migrations.AlterModelTable(
            name='skill_tree',
            table='skill_tree',
        ),
        migrations.AlterModelTable(
            name='skill_tree_nodes',
            table='skill_tree_nodes',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
        migrations.AlterModelTable(
            name='user_skill_tree_node_completion',
            table='user_skill_tree_node_completion',
        ),
    ]
