# Generated by Django 4.1.5 on 2023-02-02 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikes',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comments'),
        ),
        migrations.AlterField(
            model_name='dislikes',
            name='skill_trees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.skill_trees'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comments'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='skill_trees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.skill_trees'),
        ),
    ]
