# Generated by Django 4.1.5 on 2023-02-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_skill_trees_nodes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_trees_nodes',
            name='parent_skill_trees_node',
            field=models.IntegerField(null=True),
        ),
    ]
