# Generated by Django 4.1.5 on 2023-01-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_auth_user_table_alter_comments_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skill_tree',
            new_name='skill_trees',
        ),
        migrations.RenameModel(
            old_name='skill_tree_nodes',
            new_name='skill_trees_nodes',
        ),
        migrations.RenameModel(
            old_name='user_skill_tree_node_completion',
            new_name='user_skill_trees_node_completion',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='skill_tree_id',
            new_name='skill_trees_id',
        ),
        migrations.RenameField(
            model_name='dislikes',
            old_name='skill_tree_id',
            new_name='skill_trees_id',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='skill_tree_id',
            new_name='skill_trees_id',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='skill_tree_id',
            new_name='skill_trees_id',
        ),
        migrations.RenameField(
            model_name='skill_trees_nodes',
            old_name='parent_skill_tree_node_id',
            new_name='parent_skill_trees_node_id',
        ),
        migrations.RenameField(
            model_name='skill_trees_nodes',
            old_name='skill_tree_id',
            new_name='skill_trees_id',
        ),
        migrations.RenameField(
            model_name='user_skill_trees_node_completion',
            old_name='skill_tree_id',
            new_name='skill_trees_id',
        ),
        migrations.AlterModelTable(
            name='auth_user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='skill_trees',
            table='skill_trees',
        ),
        migrations.AlterModelTable(
            name='skill_trees_nodes',
            table='skill_trees_nodes',
        ),
        migrations.AlterModelTable(
            name='user_skill_trees_node_completion',
            table='user_skill_trees_node_completion',
        ),
    ]
