# Generated by Django 4.1.5 on 2023-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_skill_tree_skill_trees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_trees',
            name='tag_ids',
            field=models.CharField(max_length=128),
        ),
    ]
