# Generated by Django 4.1.5 on 2023-01-31 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_skill_trees_tag_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='skill_trees_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.skill_trees'),
        ),
    ]
