# Generated by Django 4.1.5 on 2023-01-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comments_skill_trees_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='skill_trees_id',
            new_name='skill_trees',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dislikes',
            old_name='comments_id',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='dislikes',
            old_name='skill_trees_id',
            new_name='skill_trees',
        ),
        migrations.RenameField(
            model_name='dislikes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='comments_id',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='skill_trees_id',
            new_name='skill_trees',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='skill_trees_id',
            new_name='skill_trees',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skill_trees',
            old_name='tag_ids',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='skill_trees',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skill_trees_nodes',
            old_name='parent_skill_trees_node_id',
            new_name='parent_skill_trees_node',
        ),
        migrations.RenameField(
            model_name='skill_trees_nodes',
            old_name='skill_trees_id',
            new_name='skill_trees',
        ),
        migrations.RenameField(
            model_name='user_skill_trees_node_completion',
            old_name='skill_trees_id',
            new_name='skill_trees',
        ),
        migrations.RenameField(
            model_name='user_skill_trees_node_completion',
            old_name='user_id',
            new_name='user',
        ),
    ]
