# Generated by Django 4.1.5 on 2023-02-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_skill_trees_id_comments_skill_trees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
